# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "TMEP 2025"
email: "admin@psft.eu"
description: "18th Technical Meeting on Energetic Particles in Magnetic Confinement Systems"
baseurl: "/"
url: "https://gdg-x.github.io"
#permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "PSFT"
organizerAlternateName: "Plasma Science and Fusion Technology"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://psft.eu"

# Head
metaKeywords: "event, fusion, plasma, magnetic, confinement, particles, technical, meeting, seville, sevilla"
twitterAccount: "@PSFT__"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "TMEP 2025"
eventDate: "March, 2025"
typeoutTextValues: '"", "Season", "Seville", "Germany", "USA"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About TMEP 2025"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest fusion related event in the country carefully crafted for you by PSFT" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of technical talks"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Valentín de Madariaga Foundation"
eventLocationLink: ""
eventStreetAddress: "P.º de las Delicias, 7, Casco Antiguo"
eventAddressLocality: "Sevilla"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41013"
eventAddressCountry: "Spain"
eventStartTime: "2025-03-17T10:00"
eventDoorTime: "09:00"
eventEndTime: "2025-03-21T20:00"
eventPlaceCoordinates: "37.3764979, -5.9941233,878"
mapCenterCoordinates: "37.3764979, -5.9941233,878"
mapMobileCenterCoordinates: "37.3764979, -5.9941233,878"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Valentín de Madariaga Foundation"
venueFeatures: ["The Valentín de Madariaga Foundation is born in 2003 in memory of D. Valentín Madariaga y Oya"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "tmep2025"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "EUR"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
  disabled: true
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: ""
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"
  disabled: true

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=PSFT__", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://psft.eu", text: "psft.eu"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:tmep2025@psft.eu", text: "tmep2025@psft.eu"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The Plasma Science and Fusion Technology (PSFT) Group at the University of Seville aims at making fusion energy a reality for our society. A clean, sustainable and virtually unlimited energy source makes fusion the scientific and engineering challenge of the 21st century. The PSFT group seeks to answer some of the most important questions on the fusion energy quest. Based on cutting-edge technologies and state-of-the-art numerical codes, we aim at getting a better understanding of energetic particle and plasma edge physics; key areas in the development of a high confinement, self maintained burning plasma. The development of new diagnostics and experimental approaches for the most relevant experimental fusion reactors worldwide form the basis of our research. The PSFT research mission is completed with the training of the new generation of fusion scientists and engineers."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Sevilla"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: ''}
 - {title: "Hotels", information: 'Sevilla has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "", text: "InterContinental"}
     - {link: "", text: "The Hotel Rex"}
     - {link: "", text: "Westin Market Street"}
     - {link: "", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: " ", text: "InterContinental"}
     - {link: "", text: "The Hotel Rex"}
     - {link: "", text: "Westin Market Street"}
     - {link: "", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "", text: "InterContinental"}
     - {link: "", text: "The Hotel Rex"}
     - {link: "", text: "Westin Market Street"}
     - {link: "", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
